version: '3.4'

services:
  simple:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BOT=simple
    expose:
      - '8080'
    ports:
     - '8080:8080'

  steam:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BOT=steam
    expose:
      - '8081'

  wikipedia:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - BOT=wikipedia
    expose:
      - '8082'

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
